# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-05 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=150, verbose_name='slug')),
                ('published_on', models.DateField(blank=True, null=True, verbose_name='date de publication')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('moderated', models.BooleanField(default=False, verbose_name='moderated')),
                ('name', models.CharField(help_text='Block name', max_length=100, verbose_name='nom')),
                ('body', models.TextField(verbose_name='content')),
            ],
            options={
                'verbose_name_plural': 'blocks',
                'ordering': ['-created_on'],
                'verbose_name': 'block',
            },
        ),
        migrations.CreateModel(
            name='BlockMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='files/pagers/', verbose_name='File')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='caption')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pager.Block')),
            ],
            options={
                'verbose_name_plural': 'medias',
                'ordering': ['-created_on'],
                'verbose_name': 'media',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title', max_length=100, verbose_name='title')),
                ('slug', models.CharField(blank=True, max_length=150, verbose_name='slug')),
                ('is_public', models.BooleanField(default=True, help_text='Only public albums will be displayed in the default views.', verbose_name='is public')),
                ('url', models.CharField(blank=True, max_length=150, verbose_name='url')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pager.Page', verbose_name='parent page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='block',
            name='page',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pager.Page', verbose_name='page'),
        ),
    ]
