# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-05 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockmedia',
            name='header',
            field=models.BooleanField(default=False, verbose_name='image principale'),
        ),
    ]
