# Generated by Django 2.0.1 on 2018-09-21 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre')),
                ('slug', models.SlugField(help_text='Automatically built from the title. A slug is a short label generally used in URLs.', max_length=256, verbose_name='slug')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté')),
                ('is_active', models.BooleanField(default=False, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre')),
                ('product_title', models.CharField(max_length=250, verbose_name='Type de produit')),
                ('product_code', models.CharField(blank=True, max_length=250, verbose_name='Code produit sur Odoo')),
                ('slug', models.SlugField(help_text='Automatically built from the title. A slug is a short label generally used in URLs.', max_length=256, verbose_name='slug')),
                ('description', models.TextField(blank=True, max_length=2500, verbose_name='Description')),
                ('number', models.IntegerField(blank=True, max_length=5, null=True, verbose_name='Nombre de pièces')),
                ('temp_number', models.IntegerField(blank=True, max_length=5, null=True, verbose_name='Nombre de pièces temporaire')),
                ('date_availability', models.DateField(blank=True, null=True, verbose_name='Disponible en livraison à partir de')),
                ('weight', models.PositiveIntegerField(blank=True, max_length=5, null=True, verbose_name='Poids de la pièce en grammes')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=7, max_length=7, null=True, verbose_name='Tarif TTC')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté')),
                ('category', models.ForeignKey(blank=True, help_text='Rangez ce produit dans une catégorie. Ex: Stock ou Cowfunding', null=True, on_delete=django.db.models.deletion.CASCADE, to='simpleproduct.Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_thumbnail', models.ImageField(blank=True, null=True, upload_to='static/images/simpleproduct/thumbnail/', verbose_name='Image miniature')),
                ('image_full', models.ImageField(blank=True, null=True, upload_to='static/images/simpleproduct/full/', verbose_name='Image complète')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='caption')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simpleproduct.Product')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'ordering': ['-created_on'],
            },
        ),
    ]
