# Generated by Django 2.0.1 on 2018-09-21 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpleproduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre')),
                ('slug', models.SlugField(help_text='Automatically built from the title. A slug is a short label generally used in URLs.', max_length=256, verbose_name='slug')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté')),
                ('is_active', models.BooleanField(default=False, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Rangez ce produit dans une catégorie.', null=True, on_delete=django.db.models.deletion.CASCADE, to='simpleproduct.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, help_text='Définissez le type du produit.', null=True, on_delete=django.db.models.deletion.CASCADE, to='simpleproduct.ProductType'),
        ),
    ]
