# Generated by Django 2.0.1 on 2018-09-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleproduct', '0002_auto_20180921_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Type de produit', 'verbose_name_plural': 'Types de produits'},
        ),
        migrations.AddField(
            model_name='product',
            name='max_number',
            field=models.IntegerField(blank=True, max_length=5, null=True, verbose_name='Nombre de pièces maximum'),
        ),
    ]
