# Generated by Django 2.0.1 on 2018-09-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleproduct', '0003_auto_20180921_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_selected',
            field=models.BooleanField(default=True, verbose_name='Selectionné'),
        ),
    ]
